# Generated by Django 5.0.2 on 2024-08-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('head1', models.CharField(default='', max_length=500)),
                ('head2', models.CharField(default='', max_length=500)),
                ('head3', models.IntegerField(default='', max_length=500)),
                ('pub_date', models.DateTimeField()),
                ('img', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
