# Generated by Django 5.0.2 on 2024-08-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='head3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
