# Generated by Django 5.0.2 on 2024-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_chead1_blogpost_chead2_blogpost_chead3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
    ]
